package:
  format-version: "1.0.0"
  name: "csp_apps_pic32cx_mt"
  version: "v3.0.0"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.13.0"


