format_version: v1.0
configName: pic32cx_mtsh_db
folderName: flexcom_twi_eeprom_pic32cx_mtsh_db
frameworkPath: C:\microchip\harmony\h3
processor: PIC32CX2051MTSH128
projectName: flexcom_twi_eeprom_pic32cx_mtsh_db
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CX-MT_DFP\0.1.33\PIC32CX-MTSH\atdf\PIC32CX2051MTSH128.atdf
