format_version: v1.0
configName: pic32cx_mtc_db
folderName: pic32cx_mtc_db
frameworkPath: C:\microchip\harmony\h3
processor: PIC32CX2051MTC128
projectName: pic32cx_mtc_db
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CX-MT_DFP\0.1.33\PIC32CX-MTC\atdf\PIC32CX2051MTC128.atdf
